server:
  port: 8080
spring:
  application:
    name: cerberus
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    
com:
  behl:
    cerberus:
      unsecured:
        api-path:
          swagger-v3: true
          post:
            - /users
            - /auth/login
          put: 
            - /auth/refresh
      jwt:
        secret-key: 093617ebfa4b9af9700db274ac204ffa34195494d97b9c26c23ad561de817926
        refresh-token:
          validity: 5
        access-token:
          validity: 30
      open-api:
        api-version: 1.0.0
        title: Cerberus
        description: Java Backend application using Spring-security to implement JWT based Authentication and Authorization