server:
  port: 8080
spring:
  application:
    name: cerberus
  datasource:
    url: jdbc:mysql://localhost:4407/cerberus
    username: cerberus
    password: Password@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 7480
      password: Password@123
    mongodb:
      uri: mongodb://localhost:27017/RestaurantDB
      host: localhost
      port: 27017
      database: RestaurantDB
  jackson:
    deserialization:
      fail-on-unknown-properties: true

    
com:
  behl:
    cerberus:
      token:
        access-token:
          private-key: ${JWT_PRIVATE_KEY}
          public-key: ${JWT_PUBLIC_KEY}
          validity: 30
        refresh-token:
          validity: 120
      open-api:
        enabled: true
        api-version: 1.0.0
        title: Cerberus
        description: Java Backend application using Spring-security to implement JWT based Authentication and Authorization

